// SINH TỰ ĐỘNG bởi tools/build-pixel.js — đừng sửa tay (xung đột khi gộp nhánh: chạy lại node tools/build-pixel.js).
// Sprite pixel nhóm "boss": "<nhóm>/<mã>" → dải khung assets/pixel/<nhóm>/<mã>.png. Game dùng khi bật pixel (js/pixel.js).
window.PIXEL_MANIFEST = window.PIXEL_MANIFEST || {};
Object.assign(window.PIXEL_MANIFEST, {
"boss/anvuong": {"name":"Quỷ Vương Ân","w":64,"h":64,"ax":31,"ay":62,"bbox":[5,2,57,61],"n":13,"anims":{"walk":{"start":0,"n":4,"fps":6,"loop":true},"attack":{"start":4,"n":3,"fps":8,"loop":false},"hurt":{"start":7,"n":1,"fps":8,"loop":false},"die":{"start":8,"n":3,"fps":5,"loop":false},"rage":{"start":11,"n":2,"fps":8,"loop":true}},"cd":1},
"boss/chantinh": {"name":"Chằn Tinh","w":64,"h":64,"ax":30,"ay":62,"bbox":[7,2,54,61],"n":13,"anims":{"walk":{"start":0,"n":4,"fps":6,"loop":true},"attack":{"start":4,"n":3,"fps":8,"loop":false},"hurt":{"start":7,"n":1,"fps":8,"loop":false},"die":{"start":8,"n":3,"fps":5,"loop":false},"rage":{"start":11,"n":2,"fps":6,"loop":true}},"cd":1},
"boss/daibang": {"name":"Đại Bàng Tinh","w":64,"h":64,"ax":31,"ay":61,"bbox":[2,11,59,51],"n":13,"anims":{"walk":{"start":0,"n":4,"fps":6,"loop":true},"attack":{"start":4,"n":3,"fps":8,"loop":false},"hurt":{"start":7,"n":1,"fps":8,"loop":false},"die":{"start":8,"n":3,"fps":5,"loop":false},"rage":{"start":11,"n":2,"fps":8,"loop":true}},"cd":1},
"boss/haba": {"name":"Hà Bá","w":48,"h":48,"ax":22,"ay":46,"bbox":[3,2,42,45],"n":11,"anims":{"walk":{"start":0,"n":4,"fps":6,"loop":true},"attack":{"start":4,"n":3,"fps":7,"loop":false},"hurt":{"start":7,"n":1,"fps":8,"loop":false},"die":{"start":8,"n":3,"fps":4,"loop":false}},"cd":1},
"boss/hotinh": {"name":"Hồ Tinh Chín Đuôi","w":64,"h":64,"ax":31,"ay":62,"bbox":[0,3,59,60],"n":13,"anims":{"walk":{"start":0,"n":4,"fps":6,"loop":true},"attack":{"start":4,"n":3,"fps":8,"loop":false},"hurt":{"start":7,"n":1,"fps":8,"loop":false},"die":{"start":8,"n":3,"fps":5,"loop":false},"rage":{"start":11,"n":2,"fps":6,"loop":true}},"cd":1},
"boss/ngutinh": {"name":"Ngư Tinh","w":48,"h":48,"ax":21,"ay":46,"bbox":[0,1,47,46],"n":11,"anims":{"walk":{"start":0,"n":4,"fps":6,"loop":true},"attack":{"start":4,"n":3,"fps":7,"loop":false},"hurt":{"start":7,"n":1,"fps":8,"loop":false},"die":{"start":8,"n":3,"fps":4,"loop":false}},"cd":1},
"boss/thuongluong": {"name":"Thuồng Luồng","w":64,"h":64,"ax":30,"ay":60,"bbox":[1,4,60,57],"n":13,"anims":{"walk":{"start":0,"n":4,"fps":5,"loop":true},"attack":{"start":4,"n":3,"fps":7,"loop":false},"hurt":{"start":7,"n":1,"fps":8,"loop":false},"die":{"start":8,"n":3,"fps":4,"loop":false},"rage":{"start":11,"n":2,"fps":6,"loop":true}},"cd":1},
"boss/thuytinh": {"name":"Thủy Tinh","w":64,"h":64,"ax":29,"ay":62,"bbox":[9,2,50,61],"n":11,"anims":{"walk":{"start":0,"n":4,"fps":5,"loop":true},"attack":{"start":4,"n":3,"fps":7,"loop":false},"hurt":{"start":7,"n":1,"fps":8,"loop":false},"die":{"start":8,"n":3,"fps":4,"loop":false}},"cd":1},
"boss/trieuda": {"name":"Hổ Vương Triệu Đà","w":64,"h":64,"ax":30,"ay":62,"bbox":[5,1,53,62],"n":13,"anims":{"walk":{"start":0,"n":4,"fps":6,"loop":true},"attack":{"start":4,"n":3,"fps":8,"loop":false},"hurt":{"start":7,"n":1,"fps":8,"loop":false},"die":{"start":8,"n":3,"fps":5,"loop":false},"rage":{"start":11,"n":2,"fps":6,"loop":true}},"cd":1},
});
