// SINH TỰ ĐỘNG bởi tools/build-pixel.js — đừng sửa tay (xung đột khi gộp nhánh: chạy lại node tools/build-pixel.js).
// Sprite pixel nhóm "ky-nang": "<nhóm>/<mã>" → dải khung assets/pixel/<nhóm>/<mã>.png. Game dùng khi bật pixel (js/pixel.js).
window.PIXEL_MANIFEST = window.PIXEL_MANIFEST || {};
Object.assign(window.PIXEL_MANIFEST, {
"ky-nang/baahoa-e": {"name":"Bà Hỏa · E «Khói Mù»","w":24,"h":24,"ax":12,"ay":23,"bbox":[0,0,24,24],"n":1,"anims":{"main":{"start":0,"n":1,"fps":1,"loop":true}}},
"ky-nang/baahoa-q": {"name":"Bà Hỏa · Q «Đốm Lửa»","w":24,"h":24,"ax":12,"ay":23,"bbox":[0,0,24,24],"n":1,"anims":{"main":{"start":0,"n":1,"fps":1,"loop":true}}},
"ky-nang/baahoa-r": {"name":"Bà Hỏa · R «Biển Lửa»","w":24,"h":24,"ax":12,"ay":23,"bbox":[0,0,24,24],"n":1,"anims":{"main":{"start":0,"n":1,"fps":1,"loop":true}}},
"ky-nang/baahoa-w": {"name":"Bà Hỏa · W «Lửa Lan»","w":24,"h":24,"ax":12,"ay":23,"bbox":[0,0,24,24],"n":1,"anims":{"main":{"start":0,"n":1,"fps":1,"loop":true}}},
"ky-nang/giong-e": {"name":"Thánh Gióng · E «Ngựa Sắt Phun Lửa»","w":24,"h":24,"ax":12,"ay":23,"bbox":[0,0,24,24],"n":1,"anims":{"main":{"start":0,"n":1,"fps":1,"loop":true}}},
"ky-nang/giong-q": {"name":"Thánh Gióng · Q «Gậy Tre Ngà»","w":24,"h":24,"ax":12,"ay":23,"bbox":[0,0,24,24],"n":1,"anims":{"main":{"start":0,"n":1,"fps":1,"loop":true}}},
"ky-nang/giong-r": {"name":"Thánh Gióng · R «Bay Về Trời»","w":24,"h":24,"ax":12,"ay":23,"bbox":[0,0,24,24],"n":1,"anims":{"main":{"start":0,"n":1,"fps":1,"loop":true}}},
"ky-nang/giong-w": {"name":"Thánh Gióng · W «Giáp Sắt»","w":24,"h":24,"ax":12,"ay":23,"bbox":[0,0,24,24],"n":1,"anims":{"main":{"start":0,"n":1,"fps":1,"loop":true}}},
"ky-nang/lachau-e": {"name":"Lạc Hầu · E «Đá Lăn Phong Châu»","w":24,"h":24,"ax":12,"ay":23,"bbox":[0,0,24,24],"n":1,"anims":{"main":{"start":0,"n":1,"fps":1,"loop":true}}},
"ky-nang/lachau-q": {"name":"Lạc Hầu · Q «Trống Hiệu Triệu»","w":24,"h":24,"ax":12,"ay":23,"bbox":[0,0,24,24],"n":1,"anims":{"main":{"start":0,"n":1,"fps":1,"loop":true}}},
"ky-nang/lachau-r": {"name":"Lạc Hầu · R «Lời Thề Bộ Lạc»","w":24,"h":24,"ax":12,"ay":23,"bbox":[0,0,24,24],"n":1,"anims":{"main":{"start":0,"n":1,"fps":1,"loop":true}}},
"ky-nang/lachau-w": {"name":"Lạc Hầu · W «Giáp Da Tê Gai»","w":24,"h":24,"ax":12,"ay":23,"bbox":[0,0,24,24],"n":1,"anims":{"main":{"start":0,"n":1,"fps":1,"loop":true}}},
"ky-nang/llq-e": {"name":"Lạc Long Quân · E «Gầm Biển»","w":24,"h":24,"ax":12,"ay":23,"bbox":[0,0,24,24],"n":1,"anims":{"main":{"start":0,"n":1,"fps":1,"loop":true}}},
"ky-nang/llq-q": {"name":"Lạc Long Quân · Q «Vuốt Rồng»","w":24,"h":24,"ax":12,"ay":23,"bbox":[0,0,24,24],"n":1,"anims":{"main":{"start":0,"n":1,"fps":1,"loop":true}}},
"ky-nang/llq-r": {"name":"Lạc Long Quân · R «Hóa Rồng»","w":24,"h":24,"ax":12,"ay":23,"bbox":[0,0,24,24],"n":1,"anims":{"main":{"start":0,"n":1,"fps":1,"loop":true}}},
"ky-nang/llq-w": {"name":"Lạc Long Quân · W «Vảy Rồng»","w":24,"h":24,"ax":12,"ay":23,"bbox":[0,0,24,24],"n":1,"anims":{"main":{"start":0,"n":1,"fps":1,"loop":true}}},
"ky-nang/lyngu-e": {"name":"Lý Ngư Tướng Quân · E «Quẫy Đuôi»","w":24,"h":24,"ax":12,"ay":23,"bbox":[0,0,24,24],"n":1,"anims":{"main":{"start":0,"n":1,"fps":1,"loop":true}}},
"ky-nang/lyngu-q": {"name":"Lý Ngư Tướng Quân · Q «Ngọn Giáo Vũ Môn»","w":24,"h":24,"ax":12,"ay":23,"bbox":[0,0,24,24],"n":1,"anims":{"main":{"start":0,"n":1,"fps":1,"loop":true}}},
"ky-nang/lyngu-r": {"name":"Lý Ngư Tướng Quân · R «Hóa Rồng»","w":24,"h":24,"ax":12,"ay":23,"bbox":[0,0,24,24],"n":1,"anims":{"main":{"start":0,"n":1,"fps":1,"loop":true}}},
"ky-nang/lyngu-w": {"name":"Lý Ngư Tướng Quân · W «Vảy Chép Vàng»","w":24,"h":24,"ax":12,"ay":23,"bbox":[0,0,24,24],"n":1,"anims":{"main":{"start":0,"n":1,"fps":1,"loop":true}}},
"ky-nang/ongtao-e": {"name":"Ông Táo · E «Tấu Trình Thiên Đình»","w":24,"h":24,"ax":12,"ay":23,"bbox":[0,0,24,24],"n":1,"anims":{"main":{"start":0,"n":1,"fps":1,"loop":true}}},
"ky-nang/ongtao-q": {"name":"Ông Táo · Q «Kẹp Than Hồng»","w":24,"h":24,"ax":12,"ay":23,"bbox":[0,0,24,24],"n":1,"anims":{"main":{"start":0,"n":1,"fps":1,"loop":true}}},
"ky-nang/ongtao-r": {"name":"Ông Táo · R «Cá Chép Hóa Rồng»","w":24,"h":24,"ax":12,"ay":23,"bbox":[0,0,24,24],"n":1,"anims":{"main":{"start":0,"n":1,"fps":1,"loop":true}}},
"ky-nang/ongtao-w": {"name":"Ông Táo · W «Ba Ông Đầu Rau»","w":24,"h":24,"ax":12,"ay":23,"bbox":[0,0,24,24],"n":1,"anims":{"main":{"start":0,"n":1,"fps":1,"loop":true}}},
"ky-nang/potaoapui-e": {"name":"Vua Lửa Pơtao Apui · E «Vòng Lửa»","w":24,"h":24,"ax":12,"ay":23,"bbox":[0,0,24,24],"n":1,"anims":{"main":{"start":0,"n":1,"fps":1,"loop":true}}},
"ky-nang/potaoapui-q": {"name":"Vua Lửa Pơtao Apui · Q «Gươm Lửa»","w":24,"h":24,"ax":12,"ay":23,"bbox":[0,0,24,24],"n":1,"anims":{"main":{"start":0,"n":1,"fps":1,"loop":true}}},
"ky-nang/potaoapui-r": {"name":"Vua Lửa Pơtao Apui · R «Núi Lửa Thức Giấc»","w":24,"h":24,"ax":12,"ay":23,"bbox":[0,0,24,24],"n":1,"anims":{"main":{"start":0,"n":1,"fps":1,"loop":true}}},
"ky-nang/potaoapui-w": {"name":"Vua Lửa Pơtao Apui · W «Lời Thề Núi Lửa»","w":24,"h":24,"ax":12,"ay":23,"bbox":[0,0,24,24],"n":1,"anims":{"main":{"start":0,"n":1,"fps":1,"loop":true}}},
"ky-nang/thansan-e": {"name":"Thần Săn Ba Vì · E «Gọi Hổ Ba Vì»","w":24,"h":24,"ax":12,"ay":23,"bbox":[0,0,24,24],"n":1,"anims":{"main":{"start":0,"n":1,"fps":1,"loop":true}}},
"ky-nang/thansan-q": {"name":"Thần Săn Ba Vì · Q «Phi Đao Tẩm Độc»","w":24,"h":24,"ax":12,"ay":23,"bbox":[0,0,24,24],"n":1,"anims":{"main":{"start":0,"n":1,"fps":1,"loop":true}}},
"ky-nang/thansan-r": {"name":"Thần Săn Ba Vì · R «Cuộc Săn Lớn»","w":24,"h":24,"ax":12,"ay":23,"bbox":[0,0,24,24],"n":1,"anims":{"main":{"start":0,"n":1,"fps":1,"loop":true}}},
"ky-nang/thansan-w": {"name":"Thần Săn Ba Vì · W «Nanh Hổ»","w":24,"h":24,"ax":12,"ay":23,"bbox":[0,0,24,24],"n":1,"anims":{"main":{"start":0,"n":1,"fps":1,"loop":true}}},
"ky-nang/trongdong-e": {"name":"Thần Trống Đồng · E «Mặt Trời Trống Đồng»","w":24,"h":24,"ax":12,"ay":23,"bbox":[0,0,24,24],"n":1,"anims":{"main":{"start":0,"n":1,"fps":1,"loop":true}}},
"ky-nang/trongdong-q": {"name":"Thần Trống Đồng · Q «Gõ Trống Trận»","w":24,"h":24,"ax":12,"ay":23,"bbox":[0,0,24,24],"n":1,"anims":{"main":{"start":0,"n":1,"fps":1,"loop":true}}},
"ky-nang/trongdong-r": {"name":"Thần Trống Đồng · R «Sấm Đồng»","w":24,"h":24,"ax":12,"ay":23,"bbox":[0,0,24,24],"n":1,"anims":{"main":{"start":0,"n":1,"fps":1,"loop":true}}},
"ky-nang/trongdong-w": {"name":"Thần Trống Đồng · W «Âm Vang»","w":24,"h":24,"ax":12,"ay":23,"bbox":[0,0,24,24],"n":1,"anims":{"main":{"start":0,"n":1,"fps":1,"loop":true}}},
"ky-nang/truongchi-e": {"name":"Trương Chi · E «Sương Khói Mặt Sông»","w":24,"h":24,"ax":12,"ay":23,"bbox":[0,0,24,24],"n":1,"anims":{"main":{"start":0,"n":1,"fps":1,"loop":true}}},
"ky-nang/truongchi-q": {"name":"Trương Chi · Q «Khúc Sáo Mê Hồn»","w":24,"h":24,"ax":12,"ay":23,"bbox":[0,0,24,24],"n":1,"anims":{"main":{"start":0,"n":1,"fps":1,"loop":true}}},
"ky-nang/truongchi-r": {"name":"Trương Chi · R «Khúc Ca Cuối»","w":24,"h":24,"ax":12,"ay":23,"bbox":[0,0,24,24],"n":1,"anims":{"main":{"start":0,"n":1,"fps":1,"loop":true}}},
"ky-nang/truongchi-w": {"name":"Trương Chi · W «Lời Ca Sông Nước»","w":24,"h":24,"ax":12,"ay":23,"bbox":[0,0,24,24],"n":1,"anims":{"main":{"start":0,"n":1,"fps":1,"loop":true}}},
});
