// SINH TỰ ĐỘNG bởi tools/build-pixel.js — đừng sửa tay (xung đột khi gộp nhánh: chạy lại node tools/build-pixel.js).
// Sprite pixel nhóm "tuong": "<nhóm>/<mã>" → dải khung assets/pixel/<nhóm>/<mã>.png. Game dùng khi bật pixel (js/pixel.js).
window.PIXEL_MANIFEST = window.PIXEL_MANIFEST || {};
Object.assign(window.PIXEL_MANIFEST, {
"tuong/adv": {"name":"An Dương Vương","w":32,"h":32,"ax":15,"ay":30,"bbox":[6,1,24,30],"n":14,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":6,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false}},"cd":1},
"tuong/auco": {"name":"Âu Cơ","w":32,"h":32,"ax":15,"ay":30,"bbox":[1,1,28,30],"n":15,"anims":{"portrait":{"start":0,"n":1,"fps":1,"loop":false},"idle":{"start":1,"n":3,"fps":3,"loop":true},"attack":{"start":4,"n":4,"fps":10,"loop":false},"cast":{"start":8,"n":3,"fps":8,"loop":true},"hurt":{"start":11,"n":1,"fps":8,"loop":false},"die":{"start":12,"n":3,"fps":5,"loop":false}},"cd":1},
"tuong/caong": {"name":"Thần Cá Ông","w":32,"h":32,"ax":14,"ay":30,"bbox":[1,1,27,30],"n":15,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":8,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false},"portrait":{"start":14,"n":1,"fps":1,"loop":false}},"cd":1},
"tuong/chodo": {"name":"Chàng Chèo Đò","w":32,"h":32,"ax":15,"ay":30,"bbox":[6,0,21,30],"n":14,"anims":{"idle":{"start":0,"n":2,"fps":3,"loop":true},"attack":{"start":2,"n":4,"fps":10,"loop":false},"cast":{"start":6,"n":3,"fps":8,"loop":true},"hurt":{"start":9,"n":2,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false}},"cd":1},
"tuong/cuoi": {"name":"Chú Cuội","w":32,"h":32,"ax":15,"ay":30,"bbox":[0,0,30,31],"n":15,"anims":{"portrait":{"start":0,"n":1,"fps":1,"loop":false},"idle":{"start":1,"n":3,"fps":3,"loop":true},"attack":{"start":4,"n":4,"fps":10,"loop":false},"cast":{"start":8,"n":3,"fps":8,"loop":true},"hurt":{"start":11,"n":1,"fps":8,"loop":false},"die":{"start":12,"n":3,"fps":5,"loop":false}},"cd":1},
"tuong/giong": {"name":"Thánh Gióng","w":32,"h":32,"ax":15,"ay":30,"bbox":[5,0,21,31],"n":14,"anims":{"idle":{"start":0,"n":2,"fps":3,"loop":true},"attack":{"start":2,"n":4,"fps":10,"loop":false},"cast":{"start":6,"n":3,"fps":8,"loop":true},"hurt":{"start":9,"n":2,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false}},"cd":1},
"tuong/halong": {"name":"Rồng Mẹ Hạ Long","w":32,"h":32,"ax":16,"ay":30,"bbox":[0,0,32,30],"n":15,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":8,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false},"portrait":{"start":14,"n":1,"fps":1,"loop":false}},"cd":1},
"tuong/kimquy": {"name":"Thần Kim Quy","w":32,"h":32,"ax":15,"ay":30,"bbox":[1,5,30,26],"n":15,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":8,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false},"portrait":{"start":14,"n":1,"fps":1,"loop":false}},"cd":1},
"tuong/kinhduong": {"name":"Kinh Dương Vương","w":32,"h":32,"ax":14,"ay":30,"bbox":[2,1,26,30],"n":14,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":8,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false}},"cd":1},
"tuong/kylan": {"name":"Kỳ Lân Vàng","w":32,"h":32,"ax":13,"ay":30,"bbox":[1,1,30,30],"n":15,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":8,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false},"portrait":{"start":14,"n":1,"fps":1,"loop":false}},"cd":1},
"tuong/llq": {"name":"Lạc Long Quân","w":32,"h":32,"ax":15,"ay":29,"bbox":[1,1,25,30],"n":14,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":8,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false}},"cd":1},
"tuong/longnu": {"name":"Long Nữ Động Đình","w":32,"h":32,"ax":16,"ay":30,"bbox":[2,1,29,30],"n":14,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":6,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false}},"cd":1},
"tuong/matroi": {"name":"Nữ Thần Mặt Trời","w":32,"h":32,"ax":17,"ay":30,"bbox":[1,2,29,29],"n":15,"anims":{"portrait":{"start":0,"n":1,"fps":1,"loop":false},"idle":{"start":1,"n":3,"fps":3,"loop":true},"attack":{"start":4,"n":4,"fps":10,"loop":false},"cast":{"start":8,"n":3,"fps":6,"loop":true},"hurt":{"start":11,"n":1,"fps":8,"loop":false},"die":{"start":12,"n":3,"fps":5,"loop":false}},"cd":1},
"tuong/mau": {"name":"Mẫu Thượng Ngàn","w":32,"h":32,"ax":17,"ay":30,"bbox":[1,1,29,29],"n":15,"anims":{"portrait":{"start":0,"n":1,"fps":1,"loop":false},"idle":{"start":1,"n":3,"fps":3,"loop":true},"attack":{"start":4,"n":4,"fps":10,"loop":false},"cast":{"start":8,"n":3,"fps":6,"loop":true},"hurt":{"start":11,"n":1,"fps":8,"loop":false},"die":{"start":12,"n":3,"fps":5,"loop":false}},"cd":1},
"tuong/maudia": {"name":"Mẫu Địa","w":32,"h":32,"ax":15,"ay":30,"bbox":[2,1,27,30],"n":14,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":6,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false}},"cd":1},
"tuong/mauthoai": {"name":"Mẫu Thoải","w":32,"h":32,"ax":16,"ay":30,"bbox":[1,1,30,30],"n":14,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":6,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false}},"cd":1},
"tuong/melua": {"name":"Mẹ Lúa","w":32,"h":32,"ax":15,"ay":30,"bbox":[3,1,26,30],"n":14,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":8,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false}},"cd":1},
"tuong/nghedong": {"name":"Nghê Đồng","w":32,"h":32,"ax":16,"ay":30,"bbox":[1,1,30,30],"n":15,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":8,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false},"portrait":{"start":14,"n":1,"fps":1,"loop":false}},"cd":1},
"tuong/ongho": {"name":"Chúa Sơn Lâm","w":32,"h":32,"ax":16,"ay":30,"bbox":[0,4,32,27],"n":15,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":8,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false},"portrait":{"start":14,"n":1,"fps":1,"loop":false}},"cd":1},
"tuong/tanvien": {"name":"Sơn Tinh","w":32,"h":32,"ax":15,"ay":30,"bbox":[5,0,21,31],"n":14,"anims":{"idle":{"start":0,"n":2,"fps":3,"loop":true},"attack":{"start":2,"n":4,"fps":10,"loop":false},"cast":{"start":6,"n":3,"fps":6,"loop":true},"hurt":{"start":9,"n":2,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false}},"cd":1},
"tuong/thienloi": {"name":"Thiên Lôi","w":32,"h":32,"ax":15,"ay":30,"bbox":[0,2,32,29],"n":14,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":8,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false}},"cd":1},
"tuong/trutroi": {"name":"Thần Trụ Trời","w":32,"h":32,"ax":15,"ay":30,"bbox":[1,1,30,30],"n":14,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":9,"loop":false},"cast":{"start":7,"n":3,"fps":6,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false}},"cd":1},
"tuong/viemde": {"name":"Viêm Đế Thần Nông","w":32,"h":32,"ax":17,"ay":30,"bbox":[3,1,28,30],"n":14,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":6,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false}},"cd":1},
});
