// SINH TỰ ĐỘNG bởi tools/build-pixel.js — đừng sửa tay (xung đột khi gộp nhánh: chạy lại node tools/build-pixel.js).
// Sprite pixel nhóm "tuong": "<nhóm>/<mã>" → dải khung assets/pixel/<nhóm>/<mã>.png. Game dùng khi bật pixel (js/pixel.js).
window.PIXEL_MANIFEST = window.PIXEL_MANIFEST || {};
Object.assign(window.PIXEL_MANIFEST, {
"tuong/antiem": {"name":"Mai An Tiêm","w":32,"h":32,"ax":15,"ay":30,"bbox":[7,2,23,29],"n":14,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":8,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false}},"cd":1},
"tuong/baahoa": {"name":"Bà Hỏa","w":32,"h":32,"ax":15,"ay":30,"bbox":[5,1,21,27],"n":14,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":8,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false}},"cd":1},
"tuong/caolo": {"name":"Cao Lỗ","w":32,"h":32,"ax":15,"ay":30,"bbox":[8,2,24,29],"n":14,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":8,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false}},"cd":1},
"tuong/cdt": {"name":"Chử Đồng Tử","w":32,"h":32,"ax":15,"ay":30,"bbox":[1,2,23,29],"n":14,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":8,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false}},"cd":1},
"tuong/chodo": {"name":"Chàng Chèo Đò","w":32,"h":32,"ax":15,"ay":30,"bbox":[6,0,21,30],"n":14,"anims":{"idle":{"start":0,"n":2,"fps":3,"loop":true},"attack":{"start":2,"n":4,"fps":10,"loop":false},"cast":{"start":6,"n":3,"fps":8,"loop":true},"hurt":{"start":9,"n":2,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false}},"cd":1},
"tuong/giong": {"name":"Thánh Gióng","w":32,"h":32,"ax":15,"ay":30,"bbox":[5,0,21,31],"n":14,"anims":{"idle":{"start":0,"n":2,"fps":3,"loop":true},"attack":{"start":2,"n":4,"fps":10,"loop":false},"cast":{"start":6,"n":3,"fps":8,"loop":true},"hurt":{"start":9,"n":2,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false}},"cd":1},
"tuong/lachau": {"name":"Lạc Hầu","w":32,"h":32,"ax":15,"ay":30,"bbox":[3,0,24,30],"n":14,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":8,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false}},"cd":1},
"tuong/langlieu": {"name":"Lang Liêu","w":32,"h":32,"ax":15,"ay":30,"bbox":[9,2,21,29],"n":14,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":6,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false}},"cd":1},
"tuong/lyngu": {"name":"Lý Ngư Tướng Quân","w":32,"h":32,"ax":15,"ay":30,"bbox":[5,0,24,31],"n":14,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":8,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false}},"cd":1},
"tuong/mychau": {"name":"Mỵ Châu","w":32,"h":32,"ax":15,"ay":30,"bbox":[1,3,22,28],"n":14,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":8,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false}},"cd":1},
"tuong/ongdung": {"name":"Ông Đùng","w":32,"h":32,"ax":15,"ay":30,"bbox":[0,0,32,31],"n":14,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":8,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false}},"cd":1},
"tuong/ongtao": {"name":"Ông Táo","w":32,"h":32,"ax":15,"ay":30,"bbox":[0,3,32,28],"n":14,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":8,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false}},"cd":1},
"tuong/potaoapui": {"name":"Vua Lửa Pơtao Apui","w":32,"h":32,"ax":15,"ay":30,"bbox":[4,3,24,28],"n":14,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":8,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false}},"cd":1},
"tuong/sodua": {"name":"Sọ Dừa","w":32,"h":32,"ax":15,"ay":30,"bbox":[2,10,29,21],"n":14,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":6,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false}},"cd":1},
"tuong/tanvien": {"name":"Sơn Tinh","w":32,"h":32,"ax":15,"ay":30,"bbox":[5,0,21,31],"n":14,"anims":{"idle":{"start":0,"n":2,"fps":3,"loop":true},"attack":{"start":2,"n":4,"fps":10,"loop":false},"cast":{"start":6,"n":3,"fps":6,"loop":true},"hurt":{"start":9,"n":2,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false}},"cd":1},
"tuong/thachsanh": {"name":"Thạch Sanh","w":32,"h":32,"ax":15,"ay":30,"bbox":[1,1,26,30],"n":14,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":8,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false}},"cd":1},
"tuong/thansan": {"name":"Thần Săn Ba Vì","w":32,"h":32,"ax":15,"ay":30,"bbox":[4,0,21,31],"n":14,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":8,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false}},"cd":1},
"tuong/thocong": {"name":"Thổ Công","w":32,"h":32,"ax":15,"ay":30,"bbox":[6,7,23,24],"n":14,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":8,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false}},"cd":1},
"tuong/tiendung": {"name":"Tiên Dung","w":32,"h":32,"ax":15,"ay":30,"bbox":[8,1,22,30],"n":14,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":8,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false}},"cd":1},
"tuong/trongdong": {"name":"Thần Trống Đồng","w":32,"h":32,"ax":15,"ay":30,"bbox":[1,6,28,25],"n":14,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":8,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false}},"cd":1},
"tuong/truongchi": {"name":"Trương Chi","w":32,"h":32,"ax":15,"ay":30,"bbox":[1,3,28,28],"n":14,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":6,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false}},"cd":1},
});
