// SINH TỰ ĐỘNG bởi tools/build-pixel.js — đừng sửa tay (xung đột khi gộp nhánh: chạy lại node tools/build-pixel.js).
// Sprite pixel nhóm "tuong": "<nhóm>/<mã>" → dải khung assets/pixel/<nhóm>/<mã>.png. Game dùng khi bật pixel (js/pixel.js).
window.PIXEL_MANIFEST = window.PIXEL_MANIFEST || {};
Object.assign(window.PIXEL_MANIFEST, {
"tuong/chantrau": {"name":"Trẻ Chăn Trâu","w":32,"h":32,"ax":15,"ay":30,"bbox":[7,9,19,22],"n":15,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":8,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false},"portrait":{"start":14,"n":1,"fps":1,"loop":false}},"cd":1},
"tuong/chodo": {"name":"Chàng Chèo Đò","w":32,"h":32,"ax":15,"ay":30,"bbox":[6,0,21,30],"n":14,"anims":{"idle":{"start":0,"n":2,"fps":3,"loop":true},"attack":{"start":2,"n":4,"fps":10,"loop":false},"cast":{"start":6,"n":3,"fps":8,"loop":true},"hurt":{"start":9,"n":2,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false}},"cd":1},
"tuong/chuongdong": {"name":"Thầy Chuông Đồng","w":32,"h":32,"ax":15,"ay":30,"bbox":[9,7,21,24],"n":15,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":8,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false},"portrait":{"start":14,"n":1,"fps":1,"loop":false}},"cd":1},
"tuong/dapde": {"name":"Người Đắp Đê","w":32,"h":32,"ax":15,"ay":30,"bbox":[6,1,19,30],"n":15,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":8,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false},"portrait":{"start":14,"n":1,"fps":1,"loop":false}},"cd":1},
"tuong/denroi": {"name":"Cô Thả Đèn Trời","w":32,"h":32,"ax":15,"ay":30,"bbox":[9,4,14,27],"n":15,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":8,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false},"portrait":{"start":14,"n":1,"fps":1,"loop":false}},"cd":1},
"tuong/dotnuong": {"name":"Chàng Đốt Nương","w":32,"h":32,"ax":15,"ay":30,"bbox":[6,0,19,31],"n":15,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":8,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false},"portrait":{"start":14,"n":1,"fps":1,"loop":false}},"cd":1},
"tuong/giaodong": {"name":"Dũng Sĩ Giáo Đồng","w":32,"h":32,"ax":15,"ay":30,"bbox":[4,1,21,30],"n":15,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":8,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false},"portrait":{"start":14,"n":1,"fps":1,"loop":false}},"cd":1},
"tuong/giong": {"name":"Thánh Gióng","w":32,"h":32,"ax":15,"ay":30,"bbox":[5,0,22,31],"n":14,"anims":{"idle":{"start":0,"n":2,"fps":3,"loop":true},"attack":{"start":2,"n":4,"fps":10,"loop":false},"cast":{"start":6,"n":3,"fps":8,"loop":true},"hurt":{"start":9,"n":2,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false}},"cd":1},
"tuong/haisen": {"name":"Cô Hái Sen","w":32,"h":32,"ax":15,"ay":30,"bbox":[8,3,19,28],"n":15,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":8,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false},"portrait":{"start":14,"n":1,"fps":1,"loop":false}},"cd":1},
"tuong/lactuong": {"name":"Lạc Tướng","w":32,"h":32,"ax":15,"ay":30,"bbox":[7,0,22,31],"n":15,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":8,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false},"portrait":{"start":14,"n":1,"fps":1,"loop":false}},"cd":1},
"tuong/lucsi": {"name":"Lực Sĩ Núi","w":32,"h":32,"ax":15,"ay":30,"bbox":[5,1,23,30],"n":15,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":8,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false},"portrait":{"start":14,"n":1,"fps":1,"loop":false}},"cd":1},
"tuong/nguphu": {"name":"Ngư Phủ Sông Đà","w":32,"h":32,"ax":15,"ay":30,"bbox":[6,5,19,26],"n":15,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":8,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false},"portrait":{"start":14,"n":1,"fps":1,"loop":false}},"cd":1},
"tuong/ongthoi": {"name":"Thợ Săn Ống Thổi","w":32,"h":32,"ax":15,"ay":30,"bbox":[8,5,17,26],"n":15,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":8,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false},"portrait":{"start":14,"n":1,"fps":1,"loop":false}},"cd":1},
"tuong/tanvien": {"name":"Sơn Tinh","w":32,"h":32,"ax":15,"ay":30,"bbox":[5,0,21,31],"n":14,"anims":{"idle":{"start":0,"n":2,"fps":3,"loop":true},"attack":{"start":2,"n":4,"fps":10,"loop":false},"cast":{"start":6,"n":3,"fps":6,"loop":true},"hurt":{"start":9,"n":2,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false}},"cd":1},
"tuong/thansuong": {"name":"Thần Sương Núi","w":32,"h":32,"ax":15,"ay":30,"bbox":[4,0,18,32],"n":15,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":8,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false},"portrait":{"start":14,"n":1,"fps":1,"loop":false}},"cd":1},
"tuong/thaylang": {"name":"Thầy Lang Lá Thuốc","w":32,"h":32,"ax":15,"ay":30,"bbox":[5,4,20,27],"n":15,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":8,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false},"portrait":{"start":14,"n":1,"fps":1,"loop":false}},"cd":1},
"tuong/thaymo": {"name":"Thầy Mo Lửa","w":32,"h":32,"ax":15,"ay":30,"bbox":[6,1,19,30],"n":15,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":8,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false},"portrait":{"start":14,"n":1,"fps":1,"loop":false}},"cd":1},
"tuong/thogom": {"name":"Thợ Gốm Phù Lãng","w":32,"h":32,"ax":15,"ay":30,"bbox":[9,2,19,29],"n":15,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":8,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false},"portrait":{"start":14,"n":1,"fps":1,"loop":false}},"cd":1},
"tuong/thoren": {"name":"Thợ Rèn Đông Sơn","w":32,"h":32,"ax":15,"ay":30,"bbox":[8,6,18,26],"n":15,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":8,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false},"portrait":{"start":14,"n":1,"fps":1,"loop":false}},"cd":1},
"tuong/thosan": {"name":"Thợ Săn Rừng","w":32,"h":32,"ax":15,"ay":30,"bbox":[6,3,20,28],"n":15,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":8,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false},"portrait":{"start":14,"n":1,"fps":1,"loop":false}},"cd":1},
"tuong/tre": {"name":"Dũng Sĩ Tre Làng","w":32,"h":32,"ax":15,"ay":30,"bbox":[9,4,22,27],"n":15,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":8,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false},"portrait":{"start":14,"n":1,"fps":1,"loop":false}},"cd":1},
"tuong/xathu": {"name":"Xạ Thủ Văn Lang","w":32,"h":32,"ax":15,"ay":30,"bbox":[7,0,19,31],"n":15,"anims":{"idle":{"start":0,"n":3,"fps":3,"loop":true},"attack":{"start":3,"n":4,"fps":10,"loop":false},"cast":{"start":7,"n":3,"fps":8,"loop":true},"hurt":{"start":10,"n":1,"fps":8,"loop":false},"die":{"start":11,"n":3,"fps":5,"loop":false},"portrait":{"start":14,"n":1,"fps":1,"loop":false}},"cd":1},
});
