// SINH TỰ ĐỘNG bởi tools/build-pixel.js — đừng sửa tay (xung đột khi gộp nhánh: chạy lại node tools/build-pixel.js).
// Sprite pixel nhóm "vfx": "<nhóm>/<mã>" → dải khung assets/pixel/<nhóm>/<mã>.png. Game dùng khi bật pixel (js/pixel.js).
window.PIXEL_MANIFEST = window.PIXEL_MANIFEST || {};
Object.assign(window.PIXEL_MANIFEST, {
"vfx/bang-tinh": {"name":"Tinh thể băng","w":10,"h":11,"ax":5,"ay":10,"bbox":[0,1,10,10],"n":2,"anims":{"main":{"start":0,"n":2,"fps":3,"loop":true}}},
"vfx/bong-doc": {"name":"Bong bóng độc","w":8,"h":8,"ax":3,"ay":3,"bbox":[0,0,7,7],"n":2,"anims":{"main":{"start":0,"n":2,"fps":6,"loop":true}}},
"vfx/bui-dat": {"name":"Bụi đất","w":14,"h":9,"ax":7,"ay":7,"bbox":[1,2,10,6],"n":3,"anims":{"main":{"start":0,"n":3,"fps":9,"loop":false}}},
"vfx/chem": {"name":"Vết chém","w":16,"h":16,"ax":8,"ay":8,"bbox":[2,0,14,13],"n":3,"anims":{"main":{"start":0,"n":3,"fps":12,"loop":false}}},
"vfx/chim-lac": {"name":"Chim Lạc","w":13,"h":8,"ax":6,"ay":4,"bbox":[0,1,13,6],"n":2,"anims":{"main":{"start":0,"n":2,"fps":6,"loop":true}}},
"vfx/dan-bang": {"name":"Mũi băng","w":13,"h":8,"ax":8,"ay":3,"bbox":[0,0,13,7],"n":1,"anims":{"main":{"start":0,"n":1,"fps":1,"loop":true}}},
"vfx/dan-lua": {"name":"Cầu lửa","w":14,"h":9,"ax":9,"ay":4,"bbox":[0,0,14,9],"n":2,"anims":{"main":{"start":0,"n":2,"fps":10,"loop":true}}},
"vfx/dua": {"name":"Dưa hấu","w":10,"h":10,"ax":5,"ay":5,"bbox":[0,0,10,10],"n":2,"anims":{"main":{"start":0,"n":2,"fps":8,"loop":true}}},
"vfx/gao": {"name":"Hạt gạo","w":12,"h":8,"ax":7,"ay":4,"bbox":[0,2,10,4],"n":1,"anims":{"main":{"start":0,"n":1,"fps":1,"loop":true}}},
"vfx/gio-xoay": {"name":"Xoáy khí","w":8,"h":8,"ax":4,"ay":4,"bbox":[1,2,6,4],"n":2,"anims":{"main":{"start":0,"n":2,"fps":6,"loop":true}}},
"vfx/hoa-sen": {"name":"Cánh sen","w":9,"h":9,"ax":4,"ay":4,"bbox":[0,0,9,8],"n":2,"anims":{"main":{"start":0,"n":2,"fps":8,"loop":true}}},
"vfx/hoi": {"name":"Hồi máu","w":9,"h":9,"ax":4,"ay":8,"bbox":[0,1,9,8],"n":2,"anims":{"main":{"start":0,"n":2,"fps":3,"loop":true}}},
"vfx/khoi": {"name":"Khói","w":12,"h":12,"ax":6,"ay":6,"bbox":[4,4,4,4],"n":4,"anims":{"main":{"start":0,"n":4,"fps":8,"loop":false}}},
"vfx/kim-quang": {"name":"Ánh kim","w":9,"h":9,"ax":4,"ay":4,"bbox":[1,1,7,7],"n":2,"anims":{"main":{"start":0,"n":2,"fps":10,"loop":false}}},
"vfx/la-tre": {"name":"Lá tre","w":10,"h":8,"ax":5,"ay":4,"bbox":[0,1,9,5],"n":2,"anims":{"main":{"start":0,"n":2,"fps":4,"loop":true}}},
"vfx/len-cap": {"name":"Lên cấp","w":9,"h":10,"ax":4,"ay":9,"bbox":[0,0,9,10],"n":1,"anims":{"main":{"start":0,"n":1,"fps":2,"loop":true}}},
"vfx/long-vu": {"name":"Lông vũ","w":13,"h":8,"ax":7,"ay":4,"bbox":[0,1,13,6],"n":1,"anims":{"main":{"start":0,"n":1,"fps":1,"loop":true}}},
"vfx/lua-chay": {"name":"Lửa bỏng","w":10,"h":14,"ax":5,"ay":13,"bbox":[0,0,10,14],"n":3,"anims":{"main":{"start":0,"n":3,"fps":8,"loop":true}}},
"vfx/may-doc": {"name":"Mây độc","w":16,"h":8,"ax":8,"ay":5,"bbox":[0,1,16,6],"n":2,"anims":{"main":{"start":0,"n":2,"fps":3,"loop":true}}},
"vfx/mui-ten": {"name":"Mũi tên","w":16,"h":8,"ax":10,"ay":3,"bbox":[1,2,14,3],"n":1,"anims":{"main":{"start":0,"n":1,"fps":1,"loop":true}}},
"vfx/ne-no": {"name":"Tên nỏ","w":14,"h":8,"ax":9,"ay":3,"bbox":[0,1,14,5],"n":1,"anims":{"main":{"start":0,"n":1,"fps":1,"loop":true}}},
"vfx/ngoc": {"name":"Ngọc phép","w":9,"h":9,"ax":4,"ay":4,"bbox":[0,0,9,9],"n":2,"anims":{"main":{"start":0,"n":2,"fps":6,"loop":true}}},
"vfx/no": {"name":"Vụ nổ","w":18,"h":18,"ax":9,"ay":9,"bbox":[6,6,6,6],"n":4,"anims":{"main":{"start":0,"n":4,"fps":10,"loop":false}}},
"vfx/nuoc-ban": {"name":"Nước bắn","w":14,"h":10,"ax":7,"ay":8,"bbox":[1,2,12,6],"n":3,"anims":{"main":{"start":0,"n":3,"fps":10,"loop":false}}},
"vfx/set": {"name":"Tia sét","w":9,"h":18,"ax":4,"ay":17,"bbox":[1,0,6,18],"n":2,"anims":{"main":{"start":0,"n":2,"fps":16,"loop":true}}},
"vfx/suong-lanh": {"name":"Sương lạnh","w":18,"h":8,"ax":9,"ay":4,"bbox":[0,1,18,5],"n":2,"anims":{"main":{"start":0,"n":2,"fps":4,"loop":true}}},
"vfx/ta-khi": {"name":"Tà khí","w":9,"h":9,"ax":4,"ay":4,"bbox":[0,0,8,8],"n":2,"anims":{"main":{"start":0,"n":2,"fps":8,"loop":true}}},
"vfx/trung": {"name":"Trúng đòn","w":11,"h":11,"ax":5,"ay":5,"bbox":[1,1,9,9],"n":3,"anims":{"main":{"start":0,"n":3,"fps":14,"loop":false}}},
"vfx/tuyet": {"name":"Bông tuyết","w":8,"h":8,"ax":3,"ay":3,"bbox":[0,0,7,7],"n":1,"anims":{"main":{"start":0,"n":1,"fps":1,"loop":true}}},
"vfx/xu": {"name":"Đồng xu","w":10,"h":10,"ax":5,"ay":5,"bbox":[0,0,10,10],"n":2,"anims":{"main":{"start":0,"n":2,"fps":8,"loop":true}}},
});
