// Thẻ nhận diện từng tướng (dùng cho nhóm prompt "Tướng vẽ lại cho dễ phân biệt" trong tools/build-prompts.js).
// Mục tiêu: nhận ra mỗi tướng chỉ từ BÓNG ĐEN (silhouette) và MÀU CHỦ ĐẠO, kể cả khi thu nhỏ 40 px.
// Lưu ý: tools/cat-sheet.py đưa mọi tướng về cùng chiều cao ảnh, nên "to / nhỏ" phải đọc được qua TỈ LỆ
// (đầu so với thân, độ rộng vai, chân ngắn / dài), không qua chiều cao tuyệt đối.
//   kind   human | beast (thú bốn chân / thân rắn) | spirit (thần linh, bay lơ lửng…)
//   body   tuổi, giới, vóc dáng + tỉ lệ đầu / thân
//   mark   MẢNG HÌNH ĐẶC TRƯNG lớn (đọc được ở 40 px) — không tướng nào trùng
//   colors [màu chính, màu phụ, điểm nhấn] — màu chính không trùng giữa các tướng
//   face   nét mặt riêng (không dùng mặt chibi chung)
//   outfit trang phục; weapon vũ khí / vật cầm; pose dáng đứng idle thể hiện tính cách; fx hiệu ứng chiêu
const HERO_ID = {
  // ===== KIM =====
  lactuong: { kind: 'human', body: 'adult man about 30, stocky and broad-chested, short legs, head about 1/4 of the height',
    mark: 'a HUGE fan-shaped headdress of tall white Lac-bird feathers, as tall as his torso, standing straight up',
    colors: ['polished bronze gold #C9963A', 'dark patina teal #2F6B5E', 'white feathers'],
    face: 'thick straight eyebrows, square jaw, three short tattoo lines on each cheek, confident smirk',
    outfit: 'bronze chest plate with zigzag bands, teal loincloth with a bronze-drum sun-star buckle',
    weapon: 'Dong Son boot-shaped bronze axe (riu xeo) with a curved asymmetric blade', pose: 'axe resting on the shoulder, chin up, proud wide stance',
    fx: 'a wide golden arc of the axe with Lac-bird shapes' },
  xathu: { kind: 'human', body: 'lanky teenage boy about 17, very thin and tall, long arms and legs, small head about 1/5 of the height',
    mark: 'an oversized longbow TALLER than himself held upright, plus a high topknot with ONE long single feather sticking up',
    colors: ['pale silver-grey #BFC6CC', 'steel blue #5E7A8C', 'red bowstring and arm wraps'],
    face: 'narrow focused eyes with one eye squinting, thin face, sharp nose, tiny mole under the eye',
    outfit: 'sleeveless silver-grey wrap tunic, steel-blue leg wraps, leather quiver on the hip', weapon: 'giant wooden longbow',
    pose: 'side stance, bow vertical beside him, one arrow held loosely between fingers, calm and patient', fx: 'three silver arrows with white streaks' },
  giaodong: { kind: 'human', body: 'young soldier about 20, short and compact like a block, short thick legs, head about 1/4 of the height',
    mark: 'a big ROUND bronze shield covering half his body in front plus a very long spear TWICE his height pointing up',
    colors: ['pewter grey #8A9399', 'tarnished bronze #A8742E', 'bright silver spear tip'],
    face: 'mostly hidden by a round helmet with cheek guards and a nose bar, only fierce determined eyes visible',
    outfit: 'pewter scale vest, bronze greaves', weapon: 'very long bronze-tipped spear',
    pose: 'low defensive crouch behind the shield, spear upright like a wall guard', fx: 'a spinning spear trailing silver sparks' },
  chuongdong: { kind: 'human', body: 'tiny frail old man about 75, hunched back, very thin arms, BIG bald round head about 1/3 of the height',
    mark: 'a staff with a bronze temple bell BIGGER than his head hanging from the top, held high over him',
    colors: ['off-white linen #EDE7D9', 'warm bronze #B07D3A', 'red tassel'],
    face: 'shiny bald head, NO beard, very long white eyebrows drooping down past the cheeks, eyes closed, humming mouth',
    outfit: 'loose off-white ritual robe with bronze zigzag hem, bare feet', weapon: 'bell staff',
    pose: 'hunched, lifting the bell staff overhead and ringing it, eyes closed in trance', fx: 'golden sound rings spreading from the bell' },
  nghedong: { kind: 'beast', body: 'Vietnamese nghe temple guardian beast on ALL FOURS, low and wide like a big muscular dog, short legs, large head',
    mark: 'a mane of big curly flame-shaped spirals around the head and a bushy curly tail curling up over the back',
    colors: ['dark antique bronze #8C5A2B', 'verdigris green #5FA39A', 'gold bell'],
    face: 'wide toothy grin, bulging round eyes, curly eyebrows, flat lion nose',
    outfit: 'gold bell on a red collar, verdigris patches on the bronze body', weapon: 'none, paws and bite',
    pose: 'crouched on four legs ready to pounce, tail up, playful', fx: 'bronze shockwave rings from a roar' },
  mychau: { kind: 'human', body: 'petite slim teenage princess about 16, narrow shoulders, head about 1/4 of the height',
    mark: 'a long WHITE goose-feather cloak that drapes down behind her and trails on the ground like a wide triangle (no wings), straight black hair down to the knees',
    colors: ['snow white #F7F7F2', 'pale lilac #C9C3DD', 'one small red ribbon'],
    face: 'soft sad eyes with long lashes, tiny mouth, little beauty mark on the chin',
    outfit: 'lilac silk dress under the feather cloak, pearl hairpins, purple-silver trim', weapon: 'none, she scatters white feathers',
    pose: 'one hand holding the edge of the cloak, the other hand dropping feathers, gentle head tilt', fx: 'white feathers turning into small birds' },
  kylan: { kind: 'beast', body: 'qilin on FOUR long slender deer-like legs, tall horse-like body, long neck',
    mark: 'a single long golden horn and golden flame-shaped tufts on all four legs, flowing white mane',
    colors: ['shining gold #E8B84A', 'ivory white #FFF4DC', 'jade green cloud curls'],
    face: 'noble dragon-like face with long whiskers, gentle wise eyes',
    outfit: 'gold scales on the back, ivory belly, cloud patterns on the legs, gold trim and a small halo of light behind the horn', weapon: 'horn and hooves',
    pose: 'prancing, one front hoof raised, head held high', fx: 'golden auspicious clouds and gold fire' },
  thienloi: { kind: 'spirit', body: 'huge burly thunder god, very wide shoulders twice his head width, thick arms, small head about 1/6 of the height',
    mark: 'wild spiky white hair standing straight up like lightning plus a pair of small feathered wings on the back and a giant stone axe',
    colors: ['storm indigo #4A5578', 'steel silver #C8D0DA', 'electric yellow #FFE14A'],
    face: 'thick angry eyebrows, square jaw, gritted teeth in a fierce grin, yellow glowing eyes',
    outfit: 'indigo armor with yellow lightning zigzags, silver bracers, gold trim, small crackling halo', weapon: 'giant stone thunder axe on a short staff',
    pose: 'axe raised overhead with both hands, legs wide, storming', fx: 'blue-yellow lightning bolts' },
  trongdong: { kind: 'spirit', body: 'stout barrel-chested drum spirit, round body, short legs, head about 1/4 of the height',
    mark: 'a HUGE Dong Son bronze drum carried on his back, wider than his body, with the sun-star face showing',
    colors: ['polished gold-bronze #D4A23C', 'deep red-brown #7A3B1E', 'green patina'],
    face: 'big round cheeks, wide open shouting mouth, short square beard, bushy brows',
    outfit: 'red-brown wrap with bronze plates, small crown of Lac-bird feathers, purple-silver trim', weapon: 'two wooden drum mallets',
    pose: 'wide stance, one mallet raised high, shouting a war call', fx: 'golden drum-beat rings and sun-star' },
  kimquy: { kind: 'beast', body: 'giant golden turtle standing upright on short hind legs, very wide round body, no neck, short and squat',
    mark: 'a huge domed golden shell with hexagon plates covering the whole back, wider than tall',
    colors: ['turtle gold #E3B23C', 'jade green skin #5E9E7E', 'glowing red-gold claw'],
    face: 'old wise turtle face, long white eyebrows and a small white beard tuft, calm half-closed eyes',
    outfit: 'gold trim on the shell rim, small crown on the head, soft golden halo', weapon: 'one glowing golden claw raised',
    pose: 'sitting firm like a rock, one claw raised in blessing', fx: 'a golden hexagon shield dome' },
  caolo: { kind: 'human', body: 'middle-aged inventor about 45, average height, thick forearms, slight belly, head about 1/4 of the height',
    mark: 'a WIDE mechanical crossbow held horizontally, wider than his whole body, with visible bronze gears and a crank',
    colors: ['dark iron grey #5B6168', 'leather brown #7B5434', 'bronze gears'],
    face: 'trimmed square beard and mustache, furrowed focused brows, bronze magnifying lens strapped over one eye',
    outfit: 'leather apron full of tools over an iron-grey tunic, purple-silver trim', weapon: 'big repeating crossbow',
    pose: 'kneeling on one knee aiming the crossbow, one eye closed', fx: 'a burst of piercing bronze bolts' },
  adv: { kind: 'human', body: 'tall slim king about 50, long legs, straight back, head about 1/5 of the height',
    mark: 'a TALL spiral tiered crown shaped like the Co Loa spiral citadel and the magic crossbow with a glowing golden turtle-claw trigger',
    colors: ['black-indigo #2C3550', 'silver armor #AEB8C2', 'turtle-claw gold glow'],
    face: 'long thin mustache drooping down and a pointed goatee, sharp eyes, high cheekbones',
    outfit: 'black-indigo royal robe with silver armor plates, gold trim, small golden halo', weapon: 'magic crossbow',
    pose: 'crossbow held at the hip, other hand on the belt, regal and calm', fx: 'a golden turtle-claw arrow splitting into many' },

  // ===== MỘC =====
  thosan: { kind: 'human', body: 'lean wiry adult hunter, long arms, always low and bent, head about 1/4 of the height',
    mark: 'a deep oversized hood with two pointed leopard ears covering the face in shadow, and two curved hunting knives',
    colors: ['dark moss green #3E5A32', 'leaf brown #6B4A2E', 'orange glowing eyes'],
    face: 'face hidden in hood shadow, only two glowing orange eyes and a mouth scarf',
    outfit: 'leaf-patched hooded cloak, leather wraps on the shins', weapon: 'two curved hunting knives held backhand',
    pose: 'low stalking crouch, knives ready, sneaky', fx: 'green poison smoke slash' },
  tre: { kind: 'human', body: 'small skinny boy about 11, thin limbs, big feet, head about 1/3 of the height',
    mark: 'a long green bamboo pole with leaves on top, TWO times his height, held diagonally; messy spiky hair with NO headband',
    colors: ['fresh bamboo yellow-green #A8D04A', 'cream #F1E6C8', 'yellow belt'],
    face: 'missing front tooth in a big grin, freckles, spiky eyebrows',
    outfit: 'sleeveless cream shirt, yellow-green shorts, bare feet', weapon: 'bamboo pole',
    pose: 'hopping on one leg, spinning the bamboo, restless', fx: 'swirling bamboo leaves' },
  ongthoi: { kind: 'human', body: 'short stout highland man about 40, thick calves, round belly, head about 1/4 of the height',
    mark: 'an extremely long blowgun tube held HORIZONTALLY to his lips, longer than his body, and long hair tied in a low ponytail',
    colors: ['dark teal-green #2F6E5A', 'black #262626', 'white zigzag weave'],
    face: 'puffed cheeks, dotted face tattoos on the forehead, small eyes, flat nose',
    outfit: 'Central Highlands woven black loincloth with white zigzag, teal sash, bamboo dart tube on the hip', weapon: 'long bamboo blowgun',
    pose: 'leaning forward with the blowgun already at his lips, one eye aiming', fx: 'green poison darts in a fan' },
  thachsanh: { kind: 'human', body: 'tall muscular young woodcutter about 22, V-shaped torso, long legs, head about 1/5 of the height',
    mark: 'a HUGE woodcutter axe with a wide blade planted head-down in front of him and a round magic moon-lute slung on his back',
    colors: ['forest green #2E7D3A', 'tan skin', 'gold lute'],
    face: 'honest kind face, wide jaw, messy shaggy hair, small scar on the eyebrow',
    outfit: 'bare chest, forest-green loincloth with rope belt, purple-silver trim on the lute strap', weapon: 'giant axe',
    pose: 'both hands resting on the axe handle, relaxed and strong', fx: 'golden axe slash with lute notes' },
  antiem: { kind: 'human', body: 'sunburned castaway man about 30, average build, head about 1/4 of the height',
    mark: 'a shaggy straw raincoat (ao toi) like a hay cape and a HUGE striped watermelon held on his shoulder',
    colors: ['straw beige #D8C38A', 'dark watermelon green #1F5E2A', 'red melon flesh #E04848'],
    face: 'stubble beard, wind-swept rope-tied hair bun, cheerful squint',
    outfit: 'straw cape over a torn brown shirt, sea-shell necklace, purple-silver trim', weapon: 'watermelons to throw',
    pose: 'hoisting the watermelon on one shoulder, other hand waving', fx: 'exploding watermelon with gold seeds' },
  sodua: { kind: 'human', body: 'tiny boy almost completely inside a ROUND coconut, the coconut is his whole body, only small arms and legs stick out',
    mark: 'a perfectly round coconut-ball body with the top of the shell worn as a hat',
    colors: ['coconut brown #7A5230', 'young-coconut green #6FAF3C', 'cream coconut flesh'],
    face: 'kind bright eyes peeking out from the shell, chubby cheeks, small smile',
    outfit: 'purple-silver trim ring around the shell opening, small flute tied on', weapon: 'none, throws green coconuts',
    pose: 'rolling slightly sideways, playing the small flute', fx: 'coconut shell opening with light' },
  cuoi: { kind: 'human', body: 'plump cheerful man about 35, round belly, short legs, head about 1/4 of the height',
    mark: 'a magic banyan tree carried on his back, the leafy round canopy rising ABOVE his head, bigger than him',
    colors: ['banyan green #3C7F45', 'moonlight pale yellow #F4E9A8', 'silver crescent moon'],
    face: 'big goofy grin, round nose, raised eyebrows of a joker, small chin beard',
    outfit: 'pale yellow tunic, gold trim, crescent-moon pendant, small halo of moonlight', weapon: 'woodcutter axe on the shoulder',
    pose: 'grinning with the axe on the shoulder, winking', fx: 'banyan leaves spiraling with moonlight' },
  melua: { kind: 'human', body: 'plump motherly woman about 45, round soft body, wide hips, head about 1/4 of the height',
    mark: 'a BIG sheaf of golden rice cradled in her arms like a baby and a crown of rice ears',
    colors: ['ripe rice gold #E9C84A', 'young rice green #7DBF4E', 'brown earth'],
    face: 'warm smile, round rosy cheeks, smile lines around the eyes, hair in a low bun',
    outfit: 'green and gold layered robe with rice-ear embroidery, gold trim, small halo', weapon: 'rice sheaf',
    pose: 'cradling and rocking the rice sheaf, motherly', fx: 'golden rice grains swirling' },
  thaylang: { kind: 'human', body: 'very thin hunched old man about 70, bony limbs, head about 1/4 of the height',
    mark: 'a tall woven gui basket on his back overflowing with herbs and leaves, sticking up above his head',
    colors: ['sage green #8BAA6E', 'earthy tan #B89A6A', 'purple herb flowers'],
    face: 'long thin drooping mustache only (no full beard), deep wrinkles, gentle squint',
    outfit: 'sage-green tunic, rolled trousers, herb pouch', weapon: 'crooked walking stick',
    pose: 'leaning on the stick, sniffing a leaf, curious', fx: 'green healing leaves and herb steam' },
  ongho: { kind: 'beast', body: 'HUGE tiger on ALL FOURS, massive shoulders, heavy paws, long body',
    mark: 'a full real tiger shape with bold black stripes and a leafy green mantle on the shoulders',
    colors: ['tiger orange #F08A24', 'black stripes', 'jade leaf green mantle'],
    face: 'majestic tiger face, white cheek fur, a small sun-star mark on the forehead, golden eyes',
    outfit: 'bronze collar, green leaf mantle, gold trim, small halo', weapon: 'claws and fangs',
    pose: 'prowling forward, head low, tail swaying', fx: 'tiger roar with green claw slashes' },
  thansan: { kind: 'human', body: 'tall wiry hunter god about 30, long legs, narrow waist, head about 1/5 of the height',
    mark: 'a deer-skull headdress with BIG branching antlers and a fur cape',
    colors: ['deep olive #556B2F', 'fur tan #C7A27A', 'red-ochre war paint'],
    face: 'red-ochre war paint stripes across the eyes, sharp cheekbones, focused stare',
    outfit: 'olive leather tunic, fur cape, bone necklace, purple-silver trim', weapon: 'long bamboo hunting spear with a leaf blade',
    pose: 'spear held low, scanning ahead, one foot forward', fx: 'green spear throw with spirit deer' },
  mau: { kind: 'spirit', body: 'tall elegant goddess, long neck, slender, head about 1/6 of the height',
    mark: 'a big FAN of giant green leaves and flowers spreading behind her like a peacock tail, and a flower crown',
    colors: ['emerald green #1E9E6A', 'flower pink #F28CB1', 'gold'],
    face: 'serene calm eyes, small knowing smile, long straight black hair',
    outfit: 'flowing emerald ao dai-style robe with forest embroidery, gold trim, small halo', weapon: 'flowering branch',
    pose: 'graceful, flowering branch held up, other hand open', fx: 'flowers and leaves blooming in a ring' },

  // ===== THỦY =====
  thansuong: { kind: 'spirit', body: 'small child-like mist spirit, slender, floating, NO legs: the body fades into a small cloud',
    mark: 'very long white hair floating UPWARD like smoke and a cloud tail instead of legs',
    colors: ['icy pale cyan #BFEAF5', 'frost white', 'deep blue ice crystal'],
    face: 'sleepy calm eyes, pale cheeks with frost freckles',
    outfit: 'misty scarf wrapping the body', weapon: 'small ice crystal held in cupped hands',
    pose: 'floating, cupping a snowflake, drifting', fx: 'frost mist and snowflakes' },
  chodo: { kind: 'human', body: 'big broad-shouldered young ferryman about 25, thick arms, short neck, head about 1/5 of the height',
    mark: 'an oversized boat oar with a WIDE flat blade, longer than his body, leaned on diagonally; shaved head with a small topknot',
    colors: ['navy indigo #2B4C7E', 'white', 'yellow rope'],
    face: 'shaved head, thick neck, friendly grin, broken nose',
    outfit: 'sleeveless white shirt, navy trousers rolled up, yellow rope belt', weapon: 'big oar',
    pose: 'leaning on the oar like a lazy giant, one hand on hip', fx: 'a wide sweep of river water' },
  haisen: { kind: 'human', body: 'small girl about 10, short, round face, head about 1/3 of the height',
    mark: 'a GIANT round lotus leaf held over her head like an umbrella and two short pigtails',
    colors: ['lotus pink #F4A3C0', 'pale water blue #9ED3E8', 'green leaf'],
    face: 'big curious eyes, gap-tooth smile, rosy cheeks',
    outfit: 'pale blue ao ba ba, pink trousers, lotus flower tucked behind the ear', weapon: 'lotus leaf umbrella and a pink lotus bud',
    pose: 'twirling the lotus leaf, swaying happily', fx: 'healing lotus petals and water drops' },
  nguphu: { kind: 'human', body: 'wiry middle-aged fisherman about 45, thin and sinewy, slightly bent knees, head about 1/4 of the height',
    mark: 'a fishing net draped over one shoulder like a cape with orange floats, and a three-pronged fish spear',
    colors: ['river teal #3E8E8A', 'faded indigo #46597A', 'orange net floats'],
    face: 'weathered skin, sunken cheeks, small goatee, knotted blue turban (khan van)',
    outfit: 'teal shirt, indigo rolled trousers, bamboo fish trap at the waist', weapon: 'three-pronged fish spear',
    pose: 'spear ready, net swinging from the shoulder', fx: 'a thrown net that tangles' },
  truongchi: { kind: 'human', body: 'thin young man about 22, slightly slouched, head about 1/4 of the height',
    mark: 'standing inside a small curved sampan boat (crescent shape under his feet) playing a long bamboo flute',
    colors: ['dusk purple-blue #5B5F9E', 'dark indigo', 'silver moon'],
    face: 'homely face: crooked nose, slightly buck teeth, eyes closed peacefully while playing',
    outfit: 'simple patched indigo shirt, conical hat hanging on his BACK (not on the head), purple-silver trim', weapon: 'long bamboo flute',
    pose: 'eyes closed playing the flute, swaying', fx: 'silver music notes and moon ripples' },
  cdt: { kind: 'human', body: 'very skinny poor young man about 20, ribs showing, long thin legs, head about 1/4 of the height',
    mark: 'only a loincloth, holding a glowing magic conical hat up in one hand like a shield and a tall sacred staff in the other',
    colors: ['sand beige #E6D3A3', 'sacred teal glow #4FC1C6', 'gold'],
    face: 'humble shy smile, messy hair, thin face, big honest eyes',
    outfit: 'plain loincloth, a sacred teal sash, purple-silver trim', weapon: 'sacred staff and glowing hat',
    pose: 'raising the glowing hat, shy but brave', fx: 'teal reviving light under the hat' },
  lyngu: { kind: 'human', body: 'athletic young general about 25, springy legs, head about 1/4 of the height',
    mark: 'a tall helmet crest shaped like a big curved CARP TAIL and a fin-shaped glaive',
    colors: ['koi orange #F2862E', 'white #FFFFFF', 'red-gold scale trim'],
    face: 'eager bright eyes, two long thin carp whiskers growing on the upper lip, confident grin',
    outfit: 'orange-white carp-scale armor, fin-shaped shoulder guards, purple-silver trim', weapon: 'fin-shaped glaive',
    pose: 'mid-leap stance with one knee raised, glaive behind', fx: 'carp leaping through a waterfall arc' },
  llq: { kind: 'human', body: 'tall powerful dragon lord about 40, broad shoulders, long legs, head about 1/6 of the height',
    mark: 'a pair of big branching DRAGON HORNS growing from his head and a long dragon-tail sash flowing behind',
    colors: ['deep sea blue #1F5FA8', 'jade #3FB59E', 'gold'],
    face: 'long flowing black hair and a long black beard, noble calm eyes, faint scales on the cheeks',
    outfit: 'deep blue robe with jade dragon scales, gold trim, small halo', weapon: 'long straight sword',
    pose: 'sword pointing down, cape and sash flowing, dignified', fx: 'a water dragon spiraling' },
  halong: { kind: 'beast', body: 'long serpentine Vietnamese dragon coiled in an S-shape, no humanoid body, small legs',
    mark: 'an S-coiled long dragon body with a flowing fin crest and a big pearl in one claw',
    colors: ['sea-foam mint #8FE3CF', 'pearl white', 'gold horns'],
    face: 'gentle motherly dragon face, long whiskers, kind eyes',
    outfit: 'gold trim on the fins, small halo', weapon: 'pearl and tail',
    pose: 'coiled, head raised, holding the pearl', fx: 'emerald islands rising from waves' },
  longnu: { kind: 'spirit', body: 'tall slender dragon princess about 20, long neck, head about 1/6 of the height',
    mark: 'a long skirt that ends in a FISH-FIN hem fanning out on the ground and small dragon horns, very long hair flowing like water',
    colors: ['aquamarine #6FD3D8', 'pearl white', 'coral pink'],
    face: 'almond eyes with teal eyeshadow, small fangs smile, pearl earrings',
    outfit: 'aquamarine silk with wave patterns, gold trim, small halo', weapon: 'big glowing dragon pearl held with both hands',
    pose: 'holding the pearl at the chest, hair floating', fx: 'pearl beams and bubbles' },
  caong: { kind: 'beast', body: 'big round whale god, the body is a huge rounded whale shape TWICE as wide as tall, tiny fin arms, very short legs',
    mark: 'a round whale silhouette with a big tail fin curling up behind and a small water spout on top of the head',
    colors: ['slate blue #3D5A80', 'cream white belly', 'barnacle gold'],
    face: 'kind old whale face with a beard of white barnacles, small gentle eyes',
    outfit: 'gold barnacle ornaments, purple-silver trim', weapon: 'none, body slam',
    pose: 'floating upright, fin arms open protectively', fx: 'a water bubble shield' },
  mauthoai: { kind: 'spirit', body: 'mature motherly goddess about 50, SEATED cross-legged on a big white lotus floating on a wave',
    mark: 'a big white lotus throne with a curling wave under it and a tall crown with a long veil',
    colors: ['royal blue #2F59B8', 'white', 'silver'],
    face: 'serene heavy-lidded eyes, plump cheeks, wise calm smile',
    outfit: 'white and royal-blue robe, silver crown with a veil, gold trim, small halo', weapon: 'silver water ladle staff',
    pose: 'seated on the lotus, one hand raised in blessing', fx: 'water whirl that holds enemies' },

  // ===== HỎA =====
  thaymo: { kind: 'human', body: 'tall gaunt shaman about 45, very thin, long arms, head about 1/5 of the height',
    mark: 'a big ROUND headdress ring of red-and-black feathers and bones around the head like a fire wheel',
    colors: ['dark plum purple #5B2C6F', 'flame orange #F47A20', 'bone white face paint'],
    face: 'white painted stripes on the face, hollow cheeks, wide crazy eyes, long chin',
    outfit: 'plum robe with orange flame hem, bead necklaces', weapon: 'gnarled staff with a burning gourd on top',
    pose: 'arms spread wide in a ritual dance, one knee up', fx: 'exploding fireballs' },
  giong: { kind: 'human', body: 'a young giant boy riding a big iron horse (mounted silhouette, horse and rider together)',
    mark: 'a black iron horse with a BURNING fire mane and the boy swinging an uprooted bamboo with roots',
    colors: ['iron black #2B2B2B', 'rust red #B23A1E', 'flame orange'],
    face: 'chubby child face with a determined frown, short spiky hair',
    outfit: 'rust-red tunic, iron armor plates, iron helmet, gold trim, small halo', weapon: 'burning uprooted bamboo',
    pose: 'horse rearing slightly, boy holding the bamboo high', fx: 'burning bamboo sweep with fire' },
  tiendung: { kind: 'human', body: 'teen princess about 17, slim, head about 1/4 of the height',
    mark: 'a big open round hand fan and hair in two big ring-shaped loops on top of the head',
    colors: ['crimson #C8243A', 'peach #F7C59F', 'gold'],
    face: 'playful sly eyes, small pouty smile, rosy cheeks',
    outfit: 'crimson ao tu than with peach sash, purple-silver trim', weapon: 'big round fan',
    pose: 'fanning playfully, hip tilted, teasing', fx: 'a gust of fire wind from the fan' },
  dotnuong: { kind: 'human', body: 'thin teenage highland farmer about 16, lanky, head about 1/4 of the height',
    mark: 'a BURNING torch on a long pole raised high and a curved machete; hair tied up with green leaves',
    colors: ['rusty red-ochre #A0462A', 'ash grey', 'ember orange'],
    face: 'soot smudges on the nose, big eager eyes, gap teeth',
    outfit: 'red-ochre loincloth, ash-grey sleeveless vest', weapon: 'torch pole and machete',
    pose: 'torch raised, machete low, ready to run', fx: 'a trail of fire on the ground' },
  denroi: { kind: 'human', body: 'little girl about 8, very short, head about 1/3 of the height',
    mark: 'a big glowing paper sky lantern held up ABOVE her head with both arms, as big as her body; two hair buns',
    colors: ['lantern yellow #FFD45A', 'tangerine #F6913A', 'red ribbon'],
    face: 'wide amazed eyes looking up, small open mouth, round cheeks',
    outfit: 'tangerine ao tu than, yellow sash', weapon: 'sky lantern',
    pose: 'on tiptoes lifting the lantern up', fx: 'small lanterns raining fire' },
  potaoapui: { kind: 'human', body: 'huge muscular highland chieftain about 40, very wide shoulders and chest, small head about 1/6 of the height',
    mark: 'a big headdress of curved BUFFALO HORNS and a large flaming sacred sword planted in front',
    colors: ['black brocade #1E1E1E', 'crimson red #B0182A', 'bronze-gold'],
    face: 'long black hair, strong jaw, stern brows, red dots painted on the cheeks',
    outfit: 'Jarai black-and-red brocade loincloth with zigzag patterns, bronze arm rings, purple-silver trim', weapon: 'flaming sword',
    pose: 'arms crossed over the sword pommel, unshakable', fx: 'a flaming sword thrust' },
  baahoa: { kind: 'spirit', body: 'mysterious woman about 40, floating slightly, slim, head about 1/5 of the height',
    mark: 'enormous hair floating upward like flames and smoke, wider than her body',
    colors: ['deep wine red #7A1426', 'black', 'orange flame tips'],
    face: 'sharp narrow eyes, dark red lips, a sly cold smile',
    outfit: 'wine-red robe with black flame patterns, purple-silver trim', weapon: 'a fireball floating in her palm',
    pose: 'floating, palm up holding fire, head tilted', fx: 'wildfire spreading' },
  kinhduong: { kind: 'human', body: 'heavy barrel-chested king about 50, wide body, thick legs, head about 1/5 of the height',
    mark: 'a ROUND sun-star crown with pointed rays and a huge broad bronze sword; full curly beard',
    colors: ['scarlet #D8352A', 'gold #E8B23A', 'black'],
    face: 'full curly red-brown beard, bushy brows, laughing loud mouth',
    outfit: 'scarlet and gold royal armor, red cape, gold trim, small halo', weapon: 'broad bronze sword',
    pose: 'both hands on the sword pommel, belly out, laughing', fx: 'a red sun shockwave' },
  viemde: { kind: 'spirit', body: 'short stocky old god about 80, slightly hunched, head about 1/4 of the height',
    mark: 'two small OX HORNS on the forehead, a leaf-and-straw cape and a long white beard',
    colors: ['burnt orange #D9622B', 'leaf green', 'sun gold'],
    face: 'long white beard, kind wrinkled eyes, chewing an herb leaf',
    outfit: 'burnt orange robe under a leaf-and-straw cape, gold trim, sun halo', weapon: 'farming hoe whose blade burns with fire',
    pose: 'leaning on the hoe, smiling, inspecting a grain stalk', fx: 'warm fire that ripens rice' },
  thoren: { kind: 'human', body: 'bulky blacksmith about 40, huge forearms, big belly, short legs, head about 1/5 of the height',
    mark: 'a giant sledgehammer with a red-hot glowing head on the shoulder; shiny bald head with a bushy black beard',
    colors: ['dark leather brown #5A3A22', 'soot grey', 'red-hot orange'],
    face: 'bald head, bushy black beard, soot on the cheeks, squinting from the heat',
    outfit: 'thick leather apron, bare muscular arms, iron wristbands', weapon: 'giant hammer',
    pose: 'hammer on the shoulder, chest out', fx: 'sparks and molten splash' },
  ongtao: { kind: 'human', body: 'plump short man about 50, round belly, short legs, head about 1/4 of the height',
    mark: 'a black official hat with two long horizontal side wings (mu canh chuon) and a small golden carp swimming around him',
    colors: ['orange-red #E0592A', 'black', 'gold carp'],
    face: 'jolly round face, thin mustache, rosy nose',
    outfit: 'orange-red robe (no trousers, bare legs — the folk joke), purple-silver trim', weapon: 'long iron fire tongs holding a glowing coal',
    pose: 'tongs held up, belly out, jolly', fx: 'kitchen fire burst' },
  matroi: { kind: 'spirit', body: 'tall radiant goddess about 25, slender, head about 1/6 of the height',
    mark: 'a HUGE sun disk with 12 pointed rays behind her, bigger than her body',
    colors: ['sun yellow-orange #FFB12E', 'white', 'red'],
    face: 'golden eyes, bright confident smile',
    outfit: 'golden-orange robe with flame hem, gold crown, gold trim', weapon: 'sun scepter',
    pose: 'both arms raised to the sky', fx: 'burning sunbeams' },

  // ===== THỔ =====
  lucsi: { kind: 'human', body: 'huge bodybuilder giant, massive shoulders 3x head width, tiny head about 1/7 of the height, short legs',
    mark: 'a big grey BOULDER held on one shoulder, bigger than his head',
    colors: ['earth ochre #C99A3C', 'clay red-brown skin', 'grey boulder'],
    face: 'tiny head, wide square jaw, short beard, unibrow, proud grin',
    outfit: 'ochre loincloth, bronze wrist cuffs', weapon: 'boulder',
    pose: 'boulder on the shoulder, flexing the other arm', fx: 'boulder smash with dust' },
  auco: { kind: 'spirit', body: 'tall graceful fairy mother about 25, slender, head about 1/6 of the height',
    mark: 'BIG white crane wings spread UPWARD and OUTWARD (real wings) and a silk pouch of 100 eggs',
    colors: ['cream #FFF6E0', 'soft gold #E7C46C', 'coral pink'],
    face: 'kind motherly eyes, gentle smile, long black hair',
    outfit: 'cream robe with gold trim, coral sash, small halo', weapon: 'egg pouch and a crane-feather wand',
    pose: 'wings open, hand on the egg pouch, protective', fx: 'healing light with crane feathers' },
  langlieu: { kind: 'human', body: 'slim gentle young prince about 20, narrow shoulders, head about 1/4 of the height',
    mark: 'a tall STACK of square green banh chung cakes carried on a tray',
    colors: ['ochre yellow #E3B448', 'banana-leaf green', 'brown sash'],
    face: 'humble shy eyes, small polite smile, neat hair under a simple gold headband',
    outfit: 'ochre tunic, brown sash, purple-silver trim', weapon: 'tray of banh chung',
    pose: 'bowing slightly while offering the tray', fx: 'square and round cakes giving buffs' },
  dapde: { kind: 'human', body: 'stocky strong village woman about 40, wide hips, thick arms, head about 1/4 of the height',
    mark: 'a big CONICAL HAT (non la) on her head and a wide flat shovel on her shoulder',
    colors: ['mud brown #7A5A3A', 'indigo', 'straw yellow hat'],
    face: 'determined frown, strong cheekbones, mud splash on the cheek',
    outfit: 'mud-brown shirt, indigo trousers rolled up, mud on the legs, a basket of earth on the hip', weapon: 'flat shovel',
    pose: 'shovel on the shoulder, fist on the hip', fx: 'an earth wall rising' },
  chantrau: { kind: 'human', body: 'tiny chubby little boy about 7, the smallest hero, short legs, head about 1/2 of the height',
    mark: 'a shaved head with three small tufts of hair (trai dao kid hairstyle) and a wooden slingshot',
    colors: ['buffalo brown #8A5A2B', 'sunburned skin', 'bright yellow scarf'],
    face: 'cheeky grin, tongue out, mischievous eyes',
    outfit: 'bare chest, brown shorts, yellow scarf around the neck, bamboo flute in the belt', weapon: 'slingshot',
    pose: 'pulling the slingshot halfway, tongue out', fx: 'stunning clay pellets' },
  ongdung: { kind: 'human', body: 'giant folk man, very tall long torso, huge hands and feet, small head about 1/7 of the height',
    mark: 'a long carrying pole across his shoulders with two BIG baskets of earth, wider than his body',
    colors: ['straw yellow #D8B35A', 'dark tanned skin', 'green moss'],
    face: 'goofy friendly giant face, big nose, wide smile',
    outfit: 'straw loincloth, purple-silver trim', weapon: 'carrying pole',
    pose: 'pole balanced on the shoulders, walking happily', fx: 'thrown earth piling into a hill' },
  thocong: { kind: 'spirit', body: 'very short round old man about 80, almost as wide as tall, round belly, head about 1/3 of the height',
    mark: 'a white beard so long it reaches the belly and a calabash gourd hanging from a tall bamboo staff',
    colors: ['warm yellow-brown #B88A3E', 'white beard', 'red sash'],
    face: 'long white beard, round laughing face, small round eyes',
    outfit: 'yellow-brown robe, soft round black cap (no wings), red sash, purple-silver trim', weapon: 'bamboo staff with a gourd',
    pose: 'chuckling, holding the belly', fx: 'a protective earth light around the house' },
  tanvien: { kind: 'spirit', body: 'tall heroic young god about 25, broad shoulders, long legs, head about 1/6 of the height',
    mark: 'a crown with THREE mountain peaks and a small floating mountain hovering above his raised palm',
    colors: ['jade-olive #6F8A3C', 'gold #D9A93A', 'white clouds'],
    face: 'young heroic face, clean-shaven, strong brows, calm smile',
    outfit: 'jade-olive armor with mountain patterns, green cape, gold trim, small halo', weapon: 'magic book on the belt',
    pose: 'one hand raising a small floating mountain', fx: 'mountains rising from the ground' },
  maudia: { kind: 'spirit', body: 'tall stately earth mother about 40, strong wide shoulders, head about 1/5 of the height',
    mark: 'roots spreading out from the hem of her robe into the ground like a wide tree base, hair braided with roots and flowers',
    colors: ['terracotta #B5562F', 'deep brown', 'spring green sprouts'],
    face: 'strong motherly face, deep brown eyes, warm smile',
    outfit: 'terracotta robe with root patterns, gold crown, gold trim, small halo', weapon: 'clay jar of seeds',
    pose: 'arms open, roots spreading', fx: 'sprouts and stone shields rising' },
  thogom: { kind: 'human', body: 'young potter girl about 18, average build, head about 1/4 of the height',
    mark: 'a big round blue-glazed clay pot held over her head ready to throw, headscarf knot',
    colors: ['sand cream #E8D2A6', 'clay brown', 'blue glaze #3E6FA8'],
    face: 'clay smudge on the nose, cheerful grin, tongue at the corner of the mouth',
    outfit: 'cream apron over a clay-brown tunic, brown headscarf knot', weapon: 'clay pots',
    pose: 'pot lifted overhead, one leg bent back', fx: 'shattering pot shards' },
  trutroi: { kind: 'spirit', body: 'colossal stone giant, enormous upper body, tiny head about 1/8 of the height, thick pillar legs',
    mark: 'a tall stone pillar held upright on one shoulder, reaching above the top of his head, clouds around it',
    colors: ['stone grey #8C8C84', 'ochre bands', 'sky blue clouds'],
    face: 'stone face with cracks, heavy brow ridge, calm mighty eyes',
    outfit: 'woven rope loincloth, rocks on the shoulders, gold trim, small halo', weapon: 'sky pillar',
    pose: 'holding the pillar upright, legs planted', fx: 'the pillar slamming down' },
  lachau: { kind: 'human', body: 'lean dignified advisor about 55, straight back, head about 1/5 of the height',
    mark: 'a tall banner pole with a Lac-bird flag flying above him and a pointed hat',
    colors: ['mustard #BF9B30', 'dark brown', 'red banner'],
    face: 'long thin goatee, wise sharp eyes, raised eyebrow',
    outfit: 'mustard robe with brown collar, purple-silver trim', weapon: 'banner pole',
    pose: 'banner planted, hand raised commanding', fx: 'a golden formation circle' },
};

// Nhóm dễ nhầm (theo contact sheet docs/tuong-de-nham.png) — sắp theo mức dễ nhầm giảm dần.
const CONFUSE = [
  { name: 'Thanh niên khăn đầu + vũ khí cán dài', look: 'young man with a headband holding a long pole weapon',
    heroes: ['tre', 'ongthoi', 'chodo', 'dotnuong', 'thoren', 'chantrau', 'xathu'] },
  { name: 'Nón lá / dân làng áo nâu', look: 'villager in a conical hat and brown clothes',
    heroes: ['dapde', 'nguphu', 'truongchi', 'antiem', 'cdt'] },
  { name: 'Cụ già râu trắng chống gậy', look: 'old man with a white beard holding a staff',
    heroes: ['thaylang', 'thocong', 'viemde', 'kimquy', 'chuongdong', 'thansuong'] },
  { name: 'Nữ thần / công chúa áo dài + gậy + hào quang', look: 'slender lady in a long robe with a staff and halo',
    heroes: ['maudia', 'matroi', 'mauthoai', 'longnu', 'melua', 'mau', 'baahoa', 'mychau', 'auco'] },
  { name: 'Vua / tướng đội mũ vàng, mặc giáp', look: 'armored king or general with a gold crown or helmet',
    heroes: ['tanvien', 'kinhduong', 'adv', 'lyngu', 'trongdong', 'llq', 'lactuong', 'giaodong', 'thienloi', 'potaoapui'] },
  { name: 'Cô gái thôn quê', look: 'young village girl in a simple dress',
    heroes: ['tiendung', 'denroi', 'thogom', 'haisen'] },
  { name: 'Thú giáp bạc / tướng đi kèm hổ', look: 'silver-armored beast standing upright or a hero with a tiger',
    heroes: ['nghedong', 'kylan', 'ongho', 'mau', 'thansan'] },
  { name: 'Thợ săn trùm mũ cầm giáo', look: 'hooded hunter with a spear',
    heroes: ['thosan', 'thansan', 'ongthoi'] },
  { name: 'Áo nâu-vàng đứng thẳng cầm vật nhỏ', look: 'man in a plain brown-yellow tunic standing straight holding a small object',
    heroes: ['lachau', 'langlieu', 'caolo', 'ongdung'] },
];

module.exports = { HERO_ID, CONFUSE };
